apiVersion: v1
kind: Service
metadata:
  name: eks-bank-note-auth-ml-app-service
  namespace: default
  labels:
    app: eks-bank-note-auth-ml-app
spec:
  selector:
    app: eks-bank-note-auth-ml-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
    - 1.2.3.140